import PrivateHeader from '@/components/header/private-header';
import { PrivateProviders } from '@/components/providers/private-providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../../global.css';

export const metadata: Metadata = {
  title: 'Platform',
  description: 'Generated by create-nx-workspace',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrivateProviders>
          <div className="flex w-full flex-col h-screen">
            <PrivateHeader />
            <main className="bg-background flex size-full overflow-hidden">
              {children}
            </main>
          </div>
        </PrivateProviders>
      </body>
    </html>
  );
}
