import { Footer } from '@/components/footer/footer';
import Header from '@/components/header/header';
import { Providers } from '@/components/providers/providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './global.css';

export const metadata: Metadata = {
  title: 'Platform',
  description: 'Generated by create-nx-workspace',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <main className="bg-background">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
